# Old way
#spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
# New way
spring.jackson.datatype.datetime.adjust-dates-to-context-time-zone=false
spring.jackson.datatype.datetime.write-dates-with-context-time-zone=false

#logging.level.org.springframework.boot.autoconfigure=DEBUG

